/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        theme: {
          primary: "var(--color-primary)",
          "primary-dim": "var(--color-primary-dim)",
          "primary-muted": "var(--color-primary-muted)",
          "primary-faint": "var(--color-primary-faint)",
          "primary-glow": "var(--color-primary-glow)",
          bg: "var(--color-bg)",
          "bg-elevated": "var(--color-bg-elevated)",
          "bg-inset": "var(--color-bg-inset)",
          surface: "var(--color-surface)",
          "surface-dim": "var(--color-surface-dim)",
          "surface-bright": "var(--color-surface-bright)",
          border: "var(--color-border)",
          "border-dim": "var(--color-border-dim)",
          text: "var(--color-text)",
          "text-bright": "var(--color-text-bright)",
          "text-dim": "var(--color-text-dim)",
          "input-bg": "var(--color-input-bg)",
          "bubble-user": "var(--color-bubble-user)",
          "bubble-assistant": "var(--color-bubble-assistant)",
          "focus-ring": "var(--color-focus-ring)",
          hover: "var(--color-hover)",
          success: "#22c55e",
          "success-dim": "rgba(34, 197, 94, 0.15)",
          warning: "#f59e0b",
          "warning-dim": "rgba(245, 158, 11, 0.15)",
          danger: "#ef4444",
          "danger-dim": "rgba(239, 68, 68, 0.15)",
          info: "#3b82f6",
          "info-dim": "rgba(59, 130, 246, 0.15)",
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.3s ease-out",
        "glow-pulse": "glow-pulse 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
