//! Core memory models for the Local Orion hierarchy.
//!
//! Local Orion Memory Hierarchy - SAO_Orion Section 7.3 + Decentralized Trust
//! Framework runtime ethical enforcement.

use crate::layers::MemoryLayer;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A persisted memory entry shared across the four memory layers.
///
/// `ethical_hash` is reserved for runtime Superego verification, while
/// `pii_tagged` marks entries that must remain local-only under the trust
/// framework.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryEntry {
    pub id: Uuid,
    pub entity_id: Uuid,
    pub layer: MemoryLayer,
    pub content: String,
    /// 1536-dimensional embedding generated by the local identity pipeline.
    pub embedding: Option<Vec<f32>>,
    pub timestamp: DateTime<Utc>,
    /// Relationships, tags, and source provenance.
    pub metadata: serde_json::Value,
    /// Set by the identity/privacy layer for local-only storage enforcement.
    pub pii_tagged: bool,
    /// Superego signature used for immutable proof and runtime verification.
    pub ethical_hash: Option<String>,
    pub version: u32,
}

impl MemoryEntry {
    /// Returns whether the entry is restricted to local storage.
    pub fn is_local_only(&self) -> bool {
        self.pii_tagged
    }

    /// Returns whether the entry still needs a crystallization signature.
    pub fn needs_crystallization(&self) -> bool {
        self.layer != MemoryLayer::Crystallized && self.ethical_hash.is_none()
    }
}

#[cfg(test)]
mod tests {
    use super::MemoryEntry;
    use crate::layers::MemoryLayer;
    use chrono::Utc;
    use serde_json::json;
    use uuid::Uuid;

    fn sample_entry(layer: MemoryLayer, ethical_hash: Option<&str>) -> MemoryEntry {
        MemoryEntry {
            id: Uuid::new_v4(),
            entity_id: Uuid::new_v4(),
            layer,
            content: "memory".to_string(),
            embedding: None,
            timestamp: Utc::now(),
            metadata: json!({ "source": "test" }),
            pii_tagged: true,
            ethical_hash: ethical_hash.map(str::to_string),
            version: 1,
        }
    }

    #[test]
    fn pii_entries_are_local_only() {
        assert!(sample_entry(MemoryLayer::Working, None).is_local_only());
    }

    #[test]
    fn non_crystallized_entries_without_hash_need_crystallization() {
        assert!(sample_entry(MemoryLayer::Semantic, None).needs_crystallization());
        assert!(!sample_entry(MemoryLayer::Semantic, Some("sig")).needs_crystallization());
        assert!(!sample_entry(MemoryLayer::Crystallized, None).needs_crystallization());
    }
}
